doc: Update README with common badges
vertigo-web/vertigo pull request #217
Opened 2023-03-08 17:33 UTC by VersBinarii

2023-03-08 17:59 UTC, szagi3891 approved these changes

2023-03-08 18:51 UTC, sfisol submitted a review, later dismissed

2023-03-08 20:46 UTC, sfisol commented
Thank you for contributing!

Please wait until we fix the workflow...

2023-03-15 21:04 UTC, sfisol commented
Hi @VersBinarii, can you rebase?

2023-03-15 21:41 UTC, VersBinarii commented
Done

2023-03-15 22:25 UTC, sfisol requested changes

2023-03-15 22:25 UTC, sfisol commented on README.md
> +Vertigo - reactive webassembly
`#` deleted after conflict resolving

2023-03-15 22:30 UTC, VersBinarii commented on README.md
> +Vertigo - reactive webassembly
🤦🏻‍♂️ Fixed

2023-03-15 22:49 UTC, sfisol approved these changes

2023-03-16 05:26 UTC, merged